name: Copy Entire React Repo via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 65.0.53.179 >> ~/.ssh/known_hosts

      - name: Copy full repository to server (excluding node_modules)
        run: |
          rsync -avz --exclude '.git' -e "ssh -p 22" ./ root@65.0.53.179:/www/wwwroot/pdtracker.run.place
      - name: SSH and install dependencies
        run: |
          ssh -p 22 root@65.0.53.179 << 'EOF'
            if ! command -v npm &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
              apt-get install -y nodejs
            fi
            cd /www/wwwroot/pdtracker.run.place
            npm install --omit=dev
          EOF
